name: Update Activity Graph
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Generate activity graph
        uses: maurodesouza/github-readme-activity-graph-action@v1
        with:
          username: mohammedshahid-dev
          options: 'theme=tokyo-night&hide_border=true&area=true&bg_color=0b0f19'
          output_path: 'activity-graph.svg'
